### ISSUE TITLE
Facebook language settings influencing detection?

### ISSUE THREAD

**Issue by peterk** [propublica/facebook-political-ads#7]
Using the plugin it seems to base detection on the language setting the user has in Facebook. Trying it out in Turkish, Pashto and Swedish detects no ads. Given that a substantial amount of users in Germany may have a different language setting than English or German there may be a risk of ads going undetected.

**Comment by thejefflarson** [comment]
Good point, we'll have the same problem in the US with Spanish speakers. I've started in on allowing people to override their browser settings, and I plan on making the classifier stuff more automatic and by language instead of by language country pair which should fix this. The ultimate goal will be to send ads that are scoped to a country instead of a language country pair. But I need to rework the database schema a bit first.

**Comment by thejefflarson** [comment]
I've added a way for people to pick their language, once we get enough ads in a particular language/country it is trivial to classify new ads.
